# Generated by Django 6.0.2 on 2026-03-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "scientific_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("watering_interval_days", models.IntegerField(blank=True, null=True)),
                (
                    "light_requirement",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("temperature_min", models.FloatField(blank=True, null=True)),
                ("temperature_max", models.FloatField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
