# Generated by Django 6.0.2 on 2026-03-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='lıght_max',
            new_name='light_max',
        ),
    ]
