# Generated by Django 6.0.2 on 2026-03-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pots", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateMachineConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soil_moisture_min", models.FloatField(default=30)),
                ("soil_moisture_max", models.FloatField(default=65)),
                ("temperature_min", models.FloatField(default=18)),
                ("temperature_max", models.FloatField(default=28)),
                ("light_min", models.FloatField(default=200)),
                ("light_max", models.FloatField(default=800)),
                ("moisture_threshold", models.FloatField(default=30)),
                ("watering_duration_ms", models.IntegerField(default=5000)),
                ("sleep_interval_min", models.IntegerField(default=15)),
                ("auto_mode", models.BooleanField(default=True)),
                ("version", models.CharField(blank=True, max_length=20, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DigitalTwinStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("health_score", models.FloatField(blank=True, null=True)),
                (
                    "growth_stage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("predicted_height_cm", models.FloatField(blank=True, null=True)),
                (
                    "water_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "simulation_state",
                    models.CharField(
                        choices=[
                            ("stable", "Stable"),
                            ("growing", "Growing"),
                            ("stressed", "Stressed"),
                            ("critical", "Critical"),
                        ],
                        default="stable",
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "pot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_twin",
                        to="pots.pot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptimalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watering_needed", models.BooleanField(default=False)),
                ("recommended_watering_ml", models.FloatField(blank=True, null=True)),
                (
                    "light_adjustment",
                    models.CharField(
                        choices=[
                            ("increase", "Increase"),
                            ("decrease", "Decrease"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "temperature_adjustment",
                    models.CharField(
                        choices=[
                            ("increase", "Increase"),
                            ("decrease", "Decrease"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimal_decisions",
                        to="pots.pot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_growth_cm", models.FloatField(blank=True, null=True)),
                ("recommended_watering_ml", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("simulation_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_results",
                        to="pots.pot",
                    ),
                ),
            ],
        ),
    ]
