# Generated by Django 5.2.13 on 2026-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_alter_digitaltwinstatus_id_alter_optimaldecision_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationresult',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='predicted_growth_cm',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='recommended_watering_ml',
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='growth_stage',
            field=models.CharField(blank=True, choices=[('healthy_growth', 'Healthy Growth'), ('stressed_growth', 'Stressed Growth'), ('critical', 'Critical')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='health_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='stress_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='total_pots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='water_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='simulation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
