PLANT_DATA = [

    {
        "name": "Aloe Vera",
        "scientific_name": "Aloe vera",
        "category": "Sukulent",
        "description": "Şifalı özellikleriyle bilinen, az su isteyen bir sukulenttir.",
        "watering_interval_days": 12,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 10,
        "temperature_max": 35,
        "image": "plants/aloe_vera.jpg",
    },

    {
        "name": "Bonsai",
        "scientific_name": "Bonsai",
        "category": "İç mekan bitkisi",
        "description": "Minyatür ağaç formunda yetiştirilen dekoratif bir bitkidir.",
        "watering_interval_days": 5,
        "light_requirement": "Orta ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/bonsai.jpg",
    },

    {
        "name": "Fesleğen",
        "scientific_name": "Ocimum basilicum",
        "category": "Aromatik bitki",
        "description": "Güneş seven ve sık sulama isteyen aromatik bir bitkidir.",
        "watering_interval_days": 2,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/feslegen.jpg",
    },

    {
        "name": "Nane",
        "scientific_name": "Mentha",
        "category": "Aromatik bitki",
        "description": "Hızlı büyüyen ve suyu seven aromatik bir bitkidir.",
        "watering_interval_days": 2,
        "light_requirement": "Orta ışık",
        "temperature_min": 10,
        "temperature_max": 30,
        "image": "plants/nane.jpg",
    },

    {
        "name": "Kekik",
        "scientific_name": "Thymus vulgaris",
        "category": "Aromatik bitki",
        "description": "Kuraklığa dayanıklı, güneş seven aromatik bir bitkidir.",
        "watering_interval_days": 7,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 10,
        "temperature_max": 30,
        "image": "plants/kekik.jpg",
    },

    {
        "name": "Lavanta",
        "scientific_name": "Lavandula",
        "category": "Çiçekli bitki",
        "description": "Güneşi seven ve hoş kokulu çiçekleri olan bir bitkidir.",
        "watering_interval_days": 6,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 10,
        "temperature_max": 35,
        "image": "plants/lavanta.jpg",
    },

    {
        "name": "Menekşe",
        "scientific_name": "Saintpaulia",
        "category": "Çiçekli bitki",
        "description": "Küçük ve renkli çiçeklere sahip iç mekan bitkisidir.",
        "watering_interval_days": 4,
        "light_requirement": "Orta ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/menekse.jpg",
    },

    {
        "name": "Begonya",
        "scientific_name": "Begonia",
        "category": "Çiçekli bitki",
        "description": "Dekoratif yaprak ve çiçekleriyle bilinen bir bitkidir.",
        "watering_interval_days": 4,
        "light_requirement": "Orta ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/begonya.jpg",
    },

    {
        "name": "Orkide",
        "scientific_name": "Orchidaceae",
        "category": "Çiçekli bitki",
        "description": "Özel bakım isteyen zarif çiçekli bir bitkidir.",
        "watering_interval_days": 5,
        "light_requirement": "Orta ışık",
        "temperature_min": 18,
        "temperature_max": 30,
        "image": "plants/orkide.jpg",
    },

    {
        "name": "Kaktüs",
        "scientific_name": "Cactaceae",
        "category": "Sukulent",
        "description": "Çok az su isteyen, kuraklığa dayanıklı bitkilerdir.",
        "watering_interval_days": 15,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 5,
        "temperature_max": 40,
        "image": "plants/kaktus.jpg",
    },

    {
        "name": "Zamioculcas",
        "scientific_name": "Zamioculcas zamiifolia",
        "category": "İç mekan bitkisi",
        "description": "Çok dayanıklı ve az bakım isteyen bir bitkidir.",
        "watering_interval_days": 12,
        "light_requirement": "Düşük ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/zamioculcas.jpg",
    },

    {
        "name": "Areka Palmiyesi",
        "scientific_name": "Dypsis lutescens",
        "category": "İç mekan bitkisi",
        "description": "Uzun yapraklı tropikal bir iç mekan bitkisidir.",
        "watering_interval_days": 5,
        "light_requirement": "Orta ışık",
        "temperature_min": 18,
        "temperature_max": 30,
        "image": "plants/areka.jpg",
    },

    {
        "name": "Salon Palmiyesi",
        "scientific_name": "Chamaedorea elegans",
        "category": "İç mekan bitkisi",
        "description": "Gölgeye dayanıklı dekoratif bir palmiyedir.",
        "watering_interval_days": 6,
        "light_requirement": "Düşük ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/salon_palmiyesi.jpg",
    },

    {
        "name": "Barış Çiçeği",
        "scientific_name": "Spathiphyllum wallisii",
        "category": "İç mekan bitkisi",
        "description": "Nem seven ve beyaz çiçek açan bitkidir.",
        "watering_interval_days": 4,
        "light_requirement": "Düşük ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/baris_cicegi.jpg",
    },

    {
        "name": "Devetabanı Mini",
        "scientific_name": "Monstera adansonii",
        "category": "İç mekan bitkisi",
        "description": "Delikli yaprakları olan sarmaşık formunda bir bitkidir.",
        "watering_interval_days": 6,
        "light_requirement": "Orta ışık",
        "temperature_min": 18,
        "temperature_max": 30,
        "image": "plants/monstera_adansonii.jpg",
    },

    {
        "name": "Fittonia",
        "scientific_name": "Fittonia",
        "category": "İç mekan bitkisi",
        "description": "Renkli damar yaprakları olan nem seven bitkidir.",
        "watering_interval_days": 3,
        "light_requirement": "Düşük ışık",
        "temperature_min": 18,
        "temperature_max": 30,
        "image": "plants/fittonia.jpg",
    },

    {
        "name": "Aglaonema",
        "scientific_name": "Aglaonema",
        "category": "İç mekan bitkisi",
        "description": "Gölgeye dayanıklı dekoratif yapraklı bitkidir.",
        "watering_interval_days": 7,
        "light_requirement": "Düşük ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/aglaonema.jpg",
    },

    {
        "name": "Kroton",
        "scientific_name": "Codiaeum variegatum",
        "category": "İç mekan bitkisi",
        "description": "Renkli yapraklarıyla dikkat çeken bitkidir.",
        "watering_interval_days": 5,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 18,
        "temperature_max": 30,
        "image": "plants/kroton.jpg",
    },

    {
        "name": "Gül",
        "scientific_name": "Rosa",
        "category": "Çiçekli bitki",
        "description": "Klasik ve dekoratif çiçekli bir bitkidir.",
        "watering_interval_days": 3,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 10,
        "temperature_max": 30,
        "image": "plants/gul.jpg",
    },

    {
        "name": "Domates",
        "scientific_name": "Solanum lycopersicum",
        "category": "Sebze",
        "description": "Güneş ve su isteyen sebze bitkisidir.",
        "watering_interval_days": 2,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/domates.jpg",
    },

    {
        "name": "Biber",
        "scientific_name": "Capsicum",
        "category": "Sebze",
        "description": "Sıcak ortamda yetişen sebze bitkisidir.",
        "watering_interval_days": 2,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/biber.jpg",
    },

    {
        "name": "Salatalık",
        "scientific_name": "Cucumis sativus",
        "category": "Sebze",
        "description": "Bol su isteyen hızlı büyüyen bir sebzedir.",
        "watering_interval_days": 2,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/salatalik.jpg",
    },

    {
        "name": "Kabak",
        "scientific_name": "Cucurbita",
        "category": "Sebze",
        "description": "Geniş yapraklı ve hızlı büyüyen sebze bitkisidir.",
        "watering_interval_days": 2,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 15,
        "temperature_max": 30,
        "image": "plants/kabak.jpg",
    },

    {
        "name": "Soğan",
        "scientific_name": "Allium cepa",
        "category": "Sebze",
        "description": "Kök sebze olarak yetiştirilen dayanıklı bir bitkidir.",
        "watering_interval_days": 3,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 10,
        "temperature_max": 25,
        "image": "plants/sogan.jpg",
    },

    {
        "name": "Sarımsak",
        "scientific_name": "Allium sativum",
        "category": "Sebze",
        "description": "Dayanıklı ve kolay yetiştirilen kök bitkidir.",
        "watering_interval_days": 3,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 10,
        "temperature_max": 25,
        "image": "plants/sarimsak.jpg",
    },

    {
        "name": "Havuç",
        "scientific_name": "Daucus carota",
        "category": "Sebze",
        "description": "Toprak altında büyüyen kök sebzedir.",
        "watering_interval_days": 3,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 10,
        "temperature_max": 25,
        "image": "plants/havuc.jpg",
    },

    {
        "name": "Patates",
        "scientific_name": "Solanum tuberosum",
        "category": "Sebze",
        "description": "Toprak altında yetişen besin değeri yüksek sebzedir.",
        "watering_interval_days": 3,
        "light_requirement": "Orta ışık",
        "temperature_min": 10,
        "temperature_max": 25,
        "image": "plants/patates.jpg",
    },

    {
        "name": "Çilek",
        "scientific_name": "Fragaria",
        "category": "Meyve",
        "description": "Güneş seven ve tatlı meyve veren bir bitkidir.",
        "watering_interval_days": 2,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 10,
        "temperature_max": 30,
        "image": "plants/cilek.jpg",
    },

    {
        "name": "Limon Ağacı",
        "scientific_name": "Citrus limon",
        "category": "Meyve",
        "description": "Güneş isteyen ve meyve veren bir ağaçtır.",
        "watering_interval_days": 5,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 10,
        "temperature_max": 35,
        "image": "plants/limon.jpg",
    },

    {
        "name": "Portakal Ağacı",
        "scientific_name": "Citrus sinensis",
        "category": "Meyve",
        "description": "Güneşli ortamda yetişen meyve ağacıdır.",
        "watering_interval_days": 5,
        "light_requirement": "Yüksek ışık",
        "temperature_min": 10,
        "temperature_max": 35,
        "image": "plants/portakal.jpg",
    },
]