# Generated by Django 6.0.2 on 2026-03-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_code", models.CharField(max_length=100, unique=True)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "firmware_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("device_token", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="offline",
                        max_length=10,
                    ),
                ),
                ("battery_level", models.FloatField(blank=True, null=True)),
                ("is_watering", models.BooleanField(default=False)),
                (
                    "last_action",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
