# Generated by Django 6.0.2 on 2026-03-24 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plants", "0001_initial"),
        ("pots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="plants/")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile", "Mobile"),
                            ("device", "Device"),
                            ("web", "Web"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="plants.plant",
                    ),
                ),
                (
                    "pot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_images",
                        to="pots.pot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("healthy", "Healthy"),
                            ("slightly_stressed", "Slightly Stressed"),
                            ("unhealthy", "Unhealthy"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("disease_detected", models.BooleanField(default=False)),
                (
                    "disease_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("wilting_level", models.FloatField(blank=True, null=True)),
                ("dryness_level", models.FloatField(blank=True, null=True)),
                ("estimated_height_cm", models.FloatField(blank=True, null=True)),
                (
                    "growth_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("growing", "Growing"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("growth_rate", models.FloatField(blank=True, null=True)),
                (
                    "species_prediction",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("suggestion", models.TextField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="plants.plant",
                    ),
                ),
                (
                    "pot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="pots.pot",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai.plantimage",
                    ),
                ),
            ],
        ),
    ]
