# Generated by Django 5.2.13 on 2026-05-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('pots', '0003_pot_allowed_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering_needed', models.BooleanField()),
                ('recommended_watering_ml', models.FloatField()),
                ('light_adjustment', models.CharField(max_length=20)),
                ('temperature_adjustment', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pots.pot')),
            ],
        ),
    ]
