# Generated by Django 6.0.2 on 2026-03-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pots", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("soil_moisture", models.FloatField(blank=True, null=True)),
                ("light", models.FloatField(blank=True, null=True)),
                ("water_level", models.FloatField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_readings",
                        to="pots.pot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WateringHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_sec", models.IntegerField(blank=True, null=True)),
                ("water_amount_ml", models.FloatField(blank=True, null=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                ("watered_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watering_history",
                        to="pots.pot",
                    ),
                ),
            ],
        ),
    ]
