# Generated by Django 6.0.2 on 2026-03-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('water_amount_ml', models.FloatField(blank=True, null=True)),
                ('trigger_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('watered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_history', to='pots.pot')),
            ],
        ),
    ]
