# Generated by Django 6.0.2 on 2026-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='auto_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pot',
            name='moisture_threshold',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='pot',
            name='sleep_interval_min',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='pot',
            name='watering_duration_ms',
            field=models.IntegerField(default=5000),
        ),
    ]
