# Generated by Django 6.0.2 on 2026-04-21 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0002_pot_auto_mode_pot_moisture_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='shared_pots', to=settings.AUTH_USER_MODEL),
        ),
    ]
