# Generated by Django 5.2.13 on 2026-05-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0003_pot_allowed_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuzzyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('memberships', models.JSONField()),
                ('firing_rules', models.JSONField()),
                ('centroid', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuzzy_logs', to='pots.pot')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
